### PR TITLE
accordion 2 issues

### PR DESCRIPTION
**Pull request by paolomoz**
Test URLs:
- Before: https://main--bevespi--hlxsites.hlx.page/how-to-use-bevespi-inhaler
- After: https://accordion-2-third--bevespi--hlxsites.hlx.page/how-to-use-bevespi-inhaler

A couple of improvements:

- on mobile the button is a "+" or a "-"
- button is at the top of the box so it doesn't overlap with thext AND it doesnìt move (which is cumbersome for the user IMO)
- in the first box, the 4 icons are slightly bigger which looks better IMO

### CODE REVIEW

**Review by lansami — CHANGES_REQUESTED** [review]
on mobile, the expanding button is overlapping a bit the text
image

**Comment by dicagno** [comment]
> on mobile, the expanding button is overlapping a bit the text image

Agree, but wouldn't consider this a blocker for going live

**Review by dicagno — APPROVED** [review]
LGTM, just please see comment from @lansami for refinining style

**Review by lansami — APPROVED** [review]

**Comment by paolomoz** [comment]
CLS high cannot be explained.. this is succeding: https://pagespeed.web.dev/analysis/https-accordion-2-third--bevespi--hlxsites-hlx-page-how-to-use-bevespi-inhaler/nuutki00e3?form_factor=mobile

**Pull request merged**
