### PR TITLE
CLS

### LINKED ISSUE #102: CLS: degraded to 0.06+
Case history:

https://default-content-wrapper--bevespi--hlxsites.hlx.page/copd-management-resources/staying-active

https://pagespeed.web.dev/analysis/https-default-content-wrapper--bevespi--hlxsites-hlx-page-copd-management-resources-what-is-copd/8pt1qyu9sj?form_factor=mobile

https://pagespeed.web.dev/analysis/https-default-content-wrapper--bevespi--hlxsites-hlx-page-copd-management-resources-staying-active/eugp8zvk1w?form_factor=mobile

https://102-cls--bevespi--hlxsites.hlx.page/frequently-asked-questions

### PR DESCRIPTION
**Pull request by paolomoz**
Fix #102

Test URLs:
- Before: https://main--bevespi--hlxsites.hlx.page/
- After: https://102-cls--bevespi--hlxsites.hlx.page/
- Test: https://102-cls--bevespi--hlxsites.hlx.page/copd-treatment
- Test: https://102-cls--bevespi--hlxsites.hlx.page/how-to-use-bevespi-inhaler
- Test: https://102-cls--bevespi--hlxsites.hlx.page/bevespi-side-effects
- Test: https://102-cls--bevespi--hlxsites.hlx.page/copd-management-resources
- Test: https://102-cls--bevespi--hlxsites.hlx.page/about-copd/what-is-chronic-obstructive-pulmonary-disease
- Test: https://102-cls--bevespi--hlxsites.hlx.page/frequently-asked-questions

### CODE REVIEW

**Comment by paolomoz** [comment]
this got 0 CLS ! https://pagespeed.web.dev/analysis/https-102-cls--bevespi--hlxsites-hlx-page-frequently-asked-questions/u8mfohq6ow?form_factor=mobile

**Comment by paolomoz** [comment]
CLS is ZERO here :) https://pagespeed.web.dev/analysis/https-102-cls--bevespi--hlxsites-hlx-page-drafts-paolom-copd-treatment/0s1t5cp6sv?form_factor=mobile

**Comment by paolomoz** [comment]
I think that the CLS gap is coming from missing fallback for <strong>

see CLS 0 after removing all bold text: https://pagespeed.web.dev/analysis/https-102-cls--bevespi--hlxsites-hlx-page-drafts-paolom-copd-treatment/9v6jfmcb66?form_factor=mobile

CLS not 0 with bold text: https://pagespeed.web.dev/analysis/https-102-cls--bevespi--hlxsites-hlx-page-copd-treatment/ha529iwhfh?form_factor=mobile

**Comment by paolomoz** [comment]
@dicagno this is what I did to get CLS down to 0:

- removed height:auto and width:auto for img which prevented to reserve the right space before image loaded
- created 2 different fallbacks for body and headings (one is smaller one is larger adjustment)
- moved the 2 most used fonts into styles.css to load them eagerly. The main problem was the bold text which is not rendered by the fallbacks; this could be fixed and fonts moved back to fonts.css but this is already good IMO

**Review by dicagno — APPROVED** [review]
Great job! LGTM

**Pull request merged**
